// Root ESLint flat config. Rules and their reasons: docs/adr/0001-repo-layout.md
import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/** Numbers that are never "magic": identity, sign, halving/doubling, percent base. */
const ALLOWED_NUMBERS = [-1, 0, 1, 2, 100];

/** apps/* and packages/* must never depend on offline tools (ADR 0001). */
const TOOLS_IMPORT_BAN = {
  patterns: [
    {
      group: ['**/tools/**', '@keep-walking/tools-*'],
      message:
        'apps/* and packages/* must not import from tools/*. Move shared logic to packages/shared (ADR 0001).',
    },
  ],
};

/**
 * Purity of the game core (ADR 0003 C1-2, C1-4). packages/shared/src and packages/geo/src run
 * unchanged in a Worker / Durable Object from Phase 3: no wall clock, no unseeded randomness,
 * no timers, no DOM, no storage, no network. Time and seeds arrive as parameters.
 */
const IMPURE_GLOBALS = [
  'window',
  'self',
  'document',
  'navigator',
  'location',
  'localStorage',
  'sessionStorage',
  'indexedDB',
  'caches',
  'fetch',
  'XMLHttpRequest',
  'WebSocket',
  'performance',
  'crypto',
  'setTimeout',
  'setInterval',
  'setImmediate',
  'clearTimeout',
  'clearInterval',
  'clearImmediate',
  'requestAnimationFrame',
  'requestIdleCallback',
  'queueMicrotask',
].map((name) => ({
  name,
  message: `"${name}" is impure. The game core takes time, randomness and I/O as parameters (ADR 0003 C1-2).`,
}));

const IMPURE_PROPERTIES = [
  { object: 'Date', property: 'now', message: 'Pass now_ms in as a parameter (ADR 0003 C1-3).' },
  {
    object: 'Math',
    property: 'random',
    message: 'Use the seeded stream from the run seed (ADR 0003 section 6).',
  },
  {
    object: 'crypto',
    property: 'getRandomValues',
    message: 'Seeds are generated by the caller (ADR 0003 section 6).',
  },
  { object: 'globalThis', message: 'No global access in the game core (ADR 0003 C1-2).' },
];

const IMPURE_SYNTAX = [
  {
    selector: "NewExpression[callee.name='Date'][arguments.length=0]",
    message: '`new Date()` reads the wall clock. Pass now_ms in (ADR 0003 C1-3).',
  },
  {
    selector: "CallExpression[callee.name='Date']",
    message: '`Date()` reads the wall clock. Pass now_ms in (ADR 0003 C1-3).',
  },
];

/** Ajv compiles with `new Function`, which Workers forbid: tests, tools and build steps only (C1-4). */
const AJV_IMPORT_BAN = {
  group: ['ajv', 'ajv/*', 'ajv-formats', 'ajv-formats/*'],
  message:
    'No Ajv in runtime code (Workers forbid new Function). Use it only in tests or tools (ADR 0003 C1-4).',
};

/** packages/geo is a leaf: it imports nothing from the workspace (ADR 0003 B-01). */
const GEO_LEAF_BAN = {
  group: ['@keep-walking/*', '**/packages/**', '**/shared/**', '**/location/**'],
  message:
    'packages/geo is a leaf package: no @keep-walking/* or cross-package imports (ADR 0003 section 4).',
};

/** The client drives the engines only through the session reducer (ADR 0003 section 3, B-07). */
const CLIENT_ENGINE_BAN = {
  group: [
    '@keep-walking/shared/run',
    '@keep-walking/shared/reward',
    '@keep-walking/shared/hp',
    '@keep-walking/shared/src/**',
    '**/packages/**',
  ],
  message:
    'apps/client calls @keep-walking/shared/session only, never run/reward/hp directly or by path (ADR 0003 section 3).',
};

const GAME_CORE_SRC = ['packages/shared/src/**/*.ts', 'packages/geo/src/**/*.ts'];
const TEST_FILES = ['**/*.test.ts', '**/*.spec.ts'];

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.wrangler/**',
      'reports/**',
      'test-results/**',
      'playwright-report/**',
      'tools/coverage/**',
      'config/**',
      'data/**',
      'design/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strict,
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
    },
    rules: {
      // All balance values come from config (CLAUDE.md non-negotiable 3).
      'no-magic-numbers': 'off',
      '@typescript-eslint/no-magic-numbers': [
        'error',
        {
          ignore: ALLOWED_NUMBERS,
          ignoreArrayIndexes: true,
          ignoreDefaultValues: false,
          ignoreEnums: true,
          ignoreNumericLiteralTypes: true,
          ignoreReadonlyClassProperties: false,
          ignoreTypeIndexes: true,
          enforceConst: true,
          detectObjects: false,
        },
      ],
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always'],
    },
  },
  {
    files: ['apps/**/*.{ts,tsx}', 'packages/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-restricted-imports': ['error', TOOLS_IMPORT_BAN],
    },
  },
  {
    files: ['apps/**/*.{js,mjs,cjs}', 'packages/**/*.{js,mjs,cjs}'],
    rules: {
      'no-restricted-imports': ['error', TOOLS_IMPORT_BAN],
    },
  },
  // --- ADR 0003 boundaries (P2-F04-T05). Later blocks replace the import-ban options above for
  // the files they match, so each one repeats TOOLS_IMPORT_BAN. ---
  {
    files: GAME_CORE_SRC,
    ignores: TEST_FILES,
    rules: {
      'no-restricted-globals': ['error', ...IMPURE_GLOBALS],
      'no-restricted-properties': ['error', ...IMPURE_PROPERTIES],
      'no-restricted-syntax': ['error', ...IMPURE_SYNTAX],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
    },
  },
  {
    files: ['packages/shared/src/**/*.ts'],
    ignores: TEST_FILES,
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        { patterns: [...TOOLS_IMPORT_BAN.patterns, AJV_IMPORT_BAN] },
      ],
    },
  },
  {
    // Leaf rule applies to geo tests as well: fixtures come from files, not from other packages.
    files: ['packages/geo/**/*.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        { patterns: [...TOOLS_IMPORT_BAN.patterns, GEO_LEAF_BAN, AJV_IMPORT_BAN] },
      ],
    },
  },
  {
    files: ['apps/client/**/*.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        { patterns: [...TOOLS_IMPORT_BAN.patterns, CLIENT_ENGINE_BAN, AJV_IMPORT_BAN] },
      ],
    },
  },
  // No override for tools/sim/src/vectors*.ts (P1-X05 decision under ADR 0001 3.5): after
  // P1-X04 those files lint clean under the full rule set (config-derived boundaries come from
  // SimParams / EconomyRefs, example inputs are named consts in CASE). Adding a blanket
  // no-magic-numbers override would only hide future hard-coded balance values.
  {
    // Tests, golden-vector fixtures, and tool/config files may use literal numbers.
    files: [
      '**/*.test.ts',
      '**/*.spec.ts',
      '**/test/**/*.ts',
      '**/e2e/**/*.ts',
      'qa/tests/**/*.ts',
      '*.config.ts',
      '*.config.js',
    ],
    rules: {
      '@typescript-eslint/no-magic-numbers': 'off',
    },
  },
  {
    // Offline CLI tools print to the terminal.
    files: ['tools/**/*.ts'],
    languageOptions: { globals: globals.node },
    rules: {
      'no-console': 'off',
    },
  },
  {
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: { globals: globals.node },
  },
  prettier,
);
